#!/usr/bin/env python3
"""
AttackSurfaceExplorer Dynamic Script Runner

Compiles and executes dynamic security verification scripts on an Android device
via AttackSurfaceExplorer's isolated :runner Foreground Service.

Usage:
  python3 runner.py <script.java | script.dex> [options]

Examples:
  # Run a Java script (auto-compiled to DEX and pushed):
  python3 runner.py sample/TestServiceProbe.java -a "activity"

  # Run a pre-compiled DEX:
  python3 runner.py payload.dex -c net.wrlu.ase.payload.TestServiceProbe
"""

import os
import sys
import glob
import time
import json
import shutil
import logging
import argparse
import tempfile
import subprocess
from pathlib import Path

logging.basicConfig(level=logging.INFO, format='%(message)s')
logger = logging.getLogger('ase_runner')

ASE_PACKAGE = 'net.wrlu.ase'
ASE_SERVICE = f'{ASE_PACKAGE}/.script.ScriptExecutionService'
ASE_RESULT_URI = 'content://net.wrlu.ase.probe/script_result'
DEVICE_TMP_DEX = '/data/local/tmp/ase_script.dex'
DEVICE_TMP_RESULT = '/data/local/tmp/ase_result.json'

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent
ASE_CLASSES_DIR = SCRIPT_DIR / 'app' / 'build' / 'intermediates' / 'javac' / 'release' / 'compileReleaseJavaWithJavac' / 'classes'


def run_cmd(cmd, check=False):
    """Execute a local shell command and return CompletedProcess."""
    return subprocess.run(cmd, capture_output=True, text=True, check=check)


def find_android_sdk():
    """Find Android SDK root directory."""
    candidates = [
        os.environ.get('ANDROID_HOME'),
        os.environ.get('ANDROID_SDK_ROOT'),
        os.path.expanduser('~/Library/Android/sdk'),
        os.path.expanduser('~/Android/Sdk'),
    ]
    for c in candidates:
        if c and os.path.isdir(c):
            return Path(c)
    return None


def find_build_tool(tool_name):
    """Locate tool (e.g. 'd8', 'javac') from PATH or Android SDK."""
    in_path = shutil.which(tool_name)
    if in_path:
        return in_path

    sdk = find_android_sdk()
    if sdk:
        if tool_name == 'd8':
            matches = sorted(glob.glob(str(sdk / 'build-tools' / '*' / 'd8')), reverse=True)
            if matches:
                return matches[0]
            cmdline = sdk / 'cmdline-tools' / 'latest' / 'bin' / 'd8'
            if cmdline.is_file():
                return str(cmdline)

    return None


def find_android_jar():
    """Locate the latest android.jar in Android SDK."""
    sdk = find_android_sdk()
    if not sdk:
        return None
    jars = sorted(glob.glob(str(sdk / 'platforms' / '*' / 'android.jar')), reverse=True)
    return jars[0] if jars else None


def extract_class_info(java_file_path):
    """Extract full class name (package + class) from a Java source file."""
    package = ''
    class_name = Path(java_file_path).stem
    with open(java_file_path, 'r', encoding='utf-8', errors='ignore') as f:
        for line in f:
            line = line.strip()
            if line.startswith('package ') and line.endswith(';'):
                package = line[len('package '):-1].strip()
            elif 'class ' in line and ('public ' in line or not package):
                tokens = line.split()
                if 'class' in tokens:
                    idx = tokens.index('class')
                    if idx + 1 < len(tokens):
                        class_name = tokens[idx + 1].split('{')[0].strip()

    if package:
        return f'{package}.{class_name}'
    return class_name


def compile_java_to_dex(java_file, output_dex):
    """Compile a Java file to a DEX file using javac and d8."""
    javac = find_build_tool('javac')
    if not javac:
        raise RuntimeError('javac not found in PATH')

    d8 = find_build_tool('d8')
    if not d8:
        raise RuntimeError('d8 not found. Please install Android SDK build-tools or set ANDROID_HOME.')

    android_jar = find_android_jar()
    if not android_jar:
        raise RuntimeError('android.jar not found. Please install an Android platform in Android SDK.')

    logger.info('[Compile] javac: %s', javac)
    logger.info('[Compile] d8: %s', d8)
    logger.info('[Compile] android.jar: %s', android_jar)

    classpath_parts = [android_jar]
    if ASE_CLASSES_DIR.is_dir():
        classpath_parts.append(str(ASE_CLASSES_DIR))
    classpath = os.pathsep.join(classpath_parts)

    with tempfile.TemporaryDirectory() as td:
        compile_cmd = [javac, '-cp', classpath, '-d', td, str(java_file)]
        res = run_cmd(compile_cmd)
        if res.returncode != 0:
            raise RuntimeError(f'javac compilation failed:\n{res.stderr}')

        class_files = glob.glob(os.path.join(td, '**', '*.class'), recursive=True)
        if not class_files:
            raise RuntimeError('No .class files generated by javac')

        d8_cmd = [d8, '--output', td] + class_files
        res = run_cmd(d8_cmd)
        if res.returncode != 0:
            raise RuntimeError(f'd8 conversion failed:\n{res.stderr}')

        gen_dex = os.path.join(td, 'classes.dex')
        if not os.path.isfile(gen_dex):
            raise RuntimeError('d8 did not produce classes.dex')

        shutil.copyfile(gen_dex, output_dex)
        logger.info('[Compile] DEX built successfully: %d bytes', os.path.getsize(output_dex))


class AdbDevice:
    def __init__(self, serial=None):
        self.serial = serial
        self.adb_base = ['adb']
        if serial:
            self.adb_base += ['-s', serial]

    def run(self, *args, check=False):
        return subprocess.run(self.adb_base + list(args), capture_output=True, text=True, check=check)

    def shell(self, *args, check=False):
        return self.run('shell', *args, check=check)

    def push(self, local, remote):
        return self.run('push', str(local), str(remote))


def execute_on_device(device, dex_path, entry_class, args='', timeout=30):
    """Push dex and trigger ScriptExecutionService, then poll for result."""
    # 1. Push DEX file
    logger.info('[ADB] Push DEX to %s', DEVICE_TMP_DEX)
    r = device.push(dex_path, DEVICE_TMP_DEX)
    if r.returncode != 0:
        raise RuntimeError(f'Failed to push DEX to device: {r.stderr}')
    device.shell('chmod', '666', DEVICE_TMP_DEX)

    # Secondary copy to app external cache as fallback
    device.shell('mkdir', '-p', f'/sdcard/Android/data/{ASE_PACKAGE}/cache/')
    device.shell('cp', DEVICE_TMP_DEX, f'/sdcard/Android/data/{ASE_PACKAGE}/cache/ase_script.dex')

    # 2. Reset previous result in cache
    device.shell('rm', '-f', f'/sdcard/Android/data/{ASE_PACKAGE}/cache/script_result.json')

    # 3. Start foreground service
    logger.info('[ADB] Start ScriptExecutionService (:runner process)')
    start_cmd = [
        'am', 'start-foreground-service',
        '-n', ASE_SERVICE,
        '--es', 'dex_path', DEVICE_TMP_DEX,
        '--es', 'entry_class', entry_class,
        '--es', 'args', args,
        '--es', 'result_file', DEVICE_TMP_RESULT,
    ]
    r = device.shell(*start_cmd)
    if r.returncode != 0:
        logger.warning('am start-foreground-service output: %s', r.stderr)

    # 4. Poll for result via DataProvider or cache file
    logger.info('[Runner] Waiting for execution result (timeout %ds)...', timeout)
    start_time = time.time()
    last_poll_output = None

    while time.time() - start_time < timeout:
        time.sleep(0.3)

        # Strategy A: DataProvider query
        q = device.shell('content', 'query', '--uri', ASE_RESULT_URI)
        if q.returncode == 0 and 'status=' in q.stdout:
            last_poll_output = q.stdout
            status = extract_field(q.stdout, 'status')
            if status in ('success', 'error'):
                json_str = extract_json_field(q.stdout)
                if json_str:
                    try:
                        return json.loads(json_str)
                    except json.JSONDecodeError:
                        pass
                return parse_cursor_output(q.stdout)

        # Strategy B: App cache file
        cat = device.shell('cat', f'/sdcard/Android/data/{ASE_PACKAGE}/cache/script_result.json')
        if cat.returncode == 0 and cat.stdout.strip().startswith('{'):
            try:
                res = json.loads(cat.stdout.strip())
                if res.get('status') in ('success', 'error'):
                    return res
            except json.JSONDecodeError:
                pass

    raise TimeoutError(f'Script execution timed out after {timeout}s. Last output:\n{last_poll_output}')


def extract_field(text, field_name):
    prefix = f'{field_name}='
    idx = text.find(prefix)
    if idx == -1:
        return ''
    start = idx + len(prefix)
    end = text.find(',', start)
    if end == -1:
        end = text.find('\n', start)
    if end == -1:
        end = len(text)
    return text[start:end].strip()


def extract_json_field(text):
    prefix = 'json='
    idx = text.find(prefix)
    if idx == -1:
        return None
    return text[idx + len(prefix):].strip()


def parse_cursor_output(text):
    return {
        'status': extract_field(text, 'status'),
        'result': extract_field(text, 'result'),
        'stdout': extract_field(text, 'stdout'),
        'error': extract_field(text, 'error'),
        'elapsed_ms': int(extract_field(text, 'elapsed_ms') or 0),
    }


def main():
    parser = argparse.ArgumentParser(
        description='Compile and execute dynamic verification scripts inside AttackSurfaceExplorer (:runner process).')
    parser.add_argument('script', help='Path to .java source file or .dex file.')
    parser.add_argument('-c', '--entry-class', help='Entry class name (auto-detected if .java provided).')
    parser.add_argument('-a', '--args', default='', help='Arguments passed to the script run method.')
    parser.add_argument('-d', '--device', help='Target adb device serial.')
    parser.add_argument('-t', '--timeout', type=int, default=30, help='Execution timeout in seconds (default: 30).')
    parser.add_argument('-o', '--output', help='Save execution result JSON to local file.')
    parser.add_argument('--no-clean', action='store_true', help='Do not delete pushed DEX on device after execution.')
    args = parser.parse_args()

    script_path = Path(args.script)
    if not script_path.exists():
        logger.error('Error: file not found: %s', script_path)
        sys.exit(1)

    entry_class = args.entry_class
    temp_dex = None

    if script_path.suffix == '.java':
        if not entry_class:
            entry_class = extract_class_info(script_path)
        logger.info('[Target] Entry class: %s', entry_class)

        temp_dir = tempfile.mkdtemp(prefix='ase_runner_')
        temp_dex = Path(temp_dir) / 'payload.dex'
        try:
            compile_java_to_dex(script_path, temp_dex)
            dex_to_push = temp_dex
        except Exception as e:
            logger.error('[Error] Compilation failed: %s', e)
            shutil.rmtree(temp_dir, ignore_errors=True)
            sys.exit(1)
    elif script_path.suffix == '.dex':
        if not entry_class:
            logger.error('Error: --entry-class (-c) is required when executing a raw .dex file.')
            sys.exit(1)
        dex_to_push = script_path
    else:
        logger.error('Error: input file must be .java or .dex')
        sys.exit(1)

    device = AdbDevice(args.device)

    try:
        result = execute_on_device(device, dex_to_push, entry_class, args=args.args, timeout=args.timeout)
        logger.info('\n' + '=' * 20 + ' EXECUTION RESULT ' + '=' * 20)
        status = result.get('status')
        logger.info('Status:     %s', status)
        logger.info('Elapsed:    %d ms', result.get('elapsed_ms', 0))

        if result.get('result'):
            logger.info('Return Val: %s', result.get('result'))
        if result.get('stdout'):
            logger.info('Stdout:\n%s', result.get('stdout').strip())
        if result.get('error'):
            logger.info('Error / Stack:\n%s', result.get('error').strip())
        logger.info('=' * 58)

        if args.output:
            with open(args.output, 'w', encoding='utf-8') as f:
                json.dump(result, f, indent=2)
            logger.info('Result saved to %s', args.output)

        if status != 'success':
            sys.exit(1)
    except Exception as e:
        logger.error('[Error] %s', e)
        sys.exit(1)
    finally:
        if not args.no_clean:
            device.shell('rm', '-f', DEVICE_TMP_DEX)
        if temp_dex and temp_dex.parent.exists():
            shutil.rmtree(temp_dex.parent, ignore_errors=True)


if __name__ == '__main__':
    main()
